version: "4.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: new_password
      POSTGRES_DB: mydatabase01
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URL: "postgresql://myuser:new_password@db:5432/mydatabase01"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

volumes:
  postgres_data:


# services:
#   db:
#     image: postgres:15-alpine
#     environment:
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: new_password
#       POSTGRES_DB: mydatabase01
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5433:5432"

#   app:
#     build: .
#     command: npm run dev
#     ports:
#       - "3000:3000"
#     environment:
#   POSTGRES_URL: "postgresql://myuser:new_password@db:5432/mydatabase01"
#   DATABASE_URL: "postgresql://myuser:new_password@db:5432/mydatabase01"
#   volumes:
#       - .:/app
#       - node_modules:/app/node_modules
#   depends_on:
#       - db

# volumes:
#   postgres_data:
#   node_modules: